config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :about

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  has_many :upvoted_users, through: :votes, source: :user
  has_many :downvoted_users, through: :votes, source: :user
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
	user && user == owner
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
  has_many :votes, dependent: :destroy
  has_many :upvoted_topics, through: :votes, source: :topic
  has_many :downvoted_topics, through: :votes, source: :topic
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic, counter_cache: :votes_count
  validates_uniqueness_of :topic_id, scope: :user_id

  belongs_to :author, class_name: "User", foreign_key: :user_id
 
  def editable_by?(user)
    user && user == author
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create(user_id: current_user.id)

    if @topic.save
      flash[:notice] = "Thank you for upvoting!"
      redirect_to(topics_path)
    else
      flash[:notice] =  "You have already upvoted this!"
      redirect_to(topics_path)
    end
  end

  def downvote
    @topic = Topic.find(params[:id])
    @topic.votes.last.destroy
    redirect_to(topics_path)
  end

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.order("votes_count DESC")
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    @topic = current_user.topics.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if current_user.topics.find(params[:id])
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = current_user.topics.find(params[:id])
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
	alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

      alerts.join("\n").html_safe
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/about/index.html.erb
<h1>About</h1>

<h2>All for vote!</h2>

<%= link_to 'Back', topics_path %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Intro to Rails</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Intro to Rails</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li> <%= link_to("註冊", new_user_registration_path) %> </li>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("帳號設定", edit_user_registration_path )%></li>
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  <%= notice_message %>
  <%= yield %>
</div>

  <%= render "common/footer" %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Editing Topic</h1>

  <hr>
  <%= simple_form_for @topic do |f| %>
    <div class="form-group">
      <%= f.input :title %>
      <%= f.input :description %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
  <%= link_to 'Show', @topic %> |
  <%= link_to 'Back', topics_path %>
</div>

app/views/topics/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to "New topic", new_topic_path, class: "btn btn-primary pull-right" %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Title</td>
        <td>Count</td>
        <td>Like</td>
        <td>Dislike</td>
        <td>Delete</td>
      </tr>
    </thead>
    <tbody>
      <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic %></td>
        <td><%= topic.votes.size %></td>
        <td><%= button_to "+1", upvote_topic_path(topic), method: :post%></td>
        <td><%= button_to "-1", downvote_topic_path(topic), method: :post%></td>
        <% if topic.editable_by?(current_user) %>
          <td><%= link_to "Delete", topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to "About", about_index_path %>
</div>

app/views/topics/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>New Topic</h1>

  <hr>
  <%= simple_form_for @topic do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
  <%= link_to "Back", topics_path %>
</div>
  

app/views/topics/show.html.erb
<div class="col-md-12">
  <div class="group">
  	<% if @topic.editable_by?(current_user) %>
      <%= link_to "Edit", edit_topic_path(@topic), class: "btn btn-primary pull-right" %>
    <% end %>    
  </div>
  <h2><%= @topic.title %></h2>
  <p><%= @topic.description %></p>
  <%= link_to "Back", topics_path %>
</div>